### ISSUE TITLE
No SVG Tiger

### ISSUE THREAD

**Issue by tylermercier** [creadecorp/storytime#1]
please fix ASAP.

**Comment by hammerdr** [comment]
Top Priority Issue.

**Comment by sghill** [comment]
Consider an [ascii tiger](http://www.ascii-art.de/ascii/t/tiger.txt), for performance.

```
              (^\-==-/^)
              >\\ == //<
             :== q''p ==:      _,.---.._
              .__ qp __. ~.-'"'\   |   |''..
                 ^--^  | | \  \ |   , || /  '-. _______ .":
                  ;| | |    | |     |/   .^-./ _)_)__))_).'
                 / \ /      |       \ /  {/ \
             ..-'\_ \   \       ,.--'\ _ ) _/\
            |  ,_../ \- |'---"""      '-/ \  |
             --       | |            /_.   |-|
                  __' | |   ._ ___   \  )  | |__
          _,______'__ddd'_______._____""__ddd'___SK______
                  __________,______.   _._
```

**Comment by tylermercier** [comment]
I've waited long enough. Just going to accept this won't happen.

![hate_change](https://cloud.githubusercontent.com/assets/49043/11784189/0afae4de-a249-11e5-951f-5726c6da893e.jpg)

**Comment by creade** [comment]
When the future of work comes and my worthiness as a person is judged by my mean time to close github issues on repos under my name I will look back at this and _laugh_ and then presumably get back to hand mining bitcoins from the boron caves on Io or whatever.
